### ISSUE TITLE
Tests need some cleanup

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-bo#28]
Tests are way too YOLO. Some cleanup is needed. As follows:

- [x] some test scenarii need to be decoupled between each other
- [x] some test need to reduce the delay to wait for Angular/Travis
- [x] tests that look for element in a `documentsInline` list, need to use the `findElementInList` utility
- [x] some tests need a `console.log`  and screenshot cleanup
- [x] some scenario predicates need to be made compliant with the guidelines
- [x] tests that delete elements from a `documentsInline` list should do it in a standard way

**Comment by scottinet** [comment]
This is the most unexpected issue description I've seen in a long time :grinning:
