### ISSUE TITLE
Tests on Travis need better error reporting

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-bo#30]
It is often difficult to understand why test fail on Travis (especially if they succeed on local machine). We need a better mechanism to enable Travis to report errors. One suggestion could be to send (only if the tests fail) the following assets to a Google Drive:

* the screenshots
* a dump of the database
* the Kuzzle logs

The Google Drive API key would be stored in an environment variable set through the Travis UI.
All the assets would be stored in a folder that corresponds to the Travis Build ID (available through an environment variable in the test process).

**Comment by xbill82** [comment]
Also, we could set the Cucumber option `failFast` to `true` so that the assets reported correspond to a specific failed step.

**Comment by dbengsch** [comment]
If we have more than one fail, it would take more time to correct the different issues. I don't know what would be the best.

**Comment by xbill82** [comment]
My point is that, if many steps fail, it will be probably necessary to fix them separately, which means one after the other, which means many builds. In this case it's OK if builds fail fast and issues are discovered progressively.
The other case is that one issue causes many steps to fail. In this case, fixing one step (i.e. the first you see failing) is enough to fix all the others.

**Comment by dbengsch** [comment]
ok for me

**Comment by AnthonySendra** [comment]
The option `failFast` doesn't exist in current version of webdriver.io :/
