### ISSUE TITLE
No error after creating invalid index

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-bo#66]
The UI enables the user to create invalid index (e.g. with uppercase letters, not allowed by Elasticsearch). The error is triggered by Kuzzle but not shown up in the BO.

I think that, in the first place, the index creation form should perform a validation on the index name before sending the request to the Kuzzle server.

Reported by EvilTroopa on Gitter
> noticed a little problem : when I tried to create an index called "Index", there was no error on the interface but kuzzle shouted in the logs "kuzzle_1         | KuzzleServer-0 error: [2016-06-09T08:32:01.504Z]: log:error:  status=400, message=[invalid_index_name_exception] Invalid index name [Index], must be lowercase, with { index=Index }, stack=Error: [invalid_index_name_exception] Invalid index name [Index], must be lowercase, with { index=Index }"

**Comment by stafyniaksacha** [comment]
Hello !
We have improved our error system in #73.
It will be available at the next release of the kuzzle stack (RC5)
