### ISSUE TITLE
RC3: first admin creation ends up in timeout

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle-bo#70]
Title says all. Right now we have to create the first administrator account using the CLI to make the backoffice work.

**Comment by ballinette** [comment]
Strange, it should have been already fixed by #65 
maybe a regression ?

**Comment by scottinet** [comment]
Dunno. Reproducable at will: just pull kuzzleio/bo:1.0.0-RC3 or kuzzleio/bo:develop, link it to an existing kuzzle (develop branch or master branch, it does not matter), and voila.

Didn't test with the whole docker-compose stack from the BO repository.

**Comment by scottinet** [comment]
Ok this is not a problem with the back-office project. There was multiple problems with the way our docker images were created, and I solved them. The docker image `kuzzleio/bo:1.0.0-RC4` doesn't seem to suffer from this bug anymore, and the system metrics problem has also been resolved.
