### ISSUE TITLE
ESLint's errors over npm build

### ISSUE THREAD

**Issue by espinozasenior** [kuzzleio/kuzzle-bo#75]
**Environment description:**

- Mac Book PRO Mid.2009, OS X Yosemite 10.10.5

- NPM version: 3.6.0

- Docker version 1.10.1, build 9e83765

- docker-compose version 1.6.0, build unknown

**Scenario**

1. I cloned master repository from git clone prompt and I typed 'docker-compose up' command.

2. I added the BO Module as Web's Guide explain, adding the block section into docker-compose.yml file.

3. All installation ran well until the BO-Module run 'npm build'. The prompt show the ESLint's errors as you can see at the next images: 

![captura de pantalla 2016-08-03 a las 14 59 57](https://cloud.githubusercontent.com/assets/3246102/17380437/c9fad7e0-598c-11e6-856b-c8b1754df6e1.png)
![captura de pantalla 2016-08-03 a las 15 05 50](https://cloud.githubusercontent.com/assets/3246102/17380438/ca11c0f4-598c-11e6-8c8e-a2bd7eb73d0b.png)

4. However, The prompt shows the BO is running at 'http://192.168.99.100:3000' but then when I went to browser's page, it looks like below:

![captura de pantalla 2016-08-03 a las 15 09 48](https://cloud.githubusercontent.com/assets/3246102/17380464/e47981c0-598c-11e6-81c7-d2e3f738eeb5.png)

**Comment by benoitvidis** [comment]
Hi, sorry for the delay.

We are currently validating the cause and the fix but it looks it may be related to a webpack plugin issue: https://github.com/webpack/webpack/issues/2644

Waiting for the fix, you can try to comment the Dedupe plugin in webpack.config.js:
```
      // Reference: http://webpack.github.io/docs/list-of-plugins.html#dedupeplugin                                                                                                                                                          
      // Dedupe modules in the output                                                                                                                                                                                                        
      // new webpack.optimize.DedupePlugin(),
```

And then build and run again:
```
npm install tls fs
npm run build
./bin/www
```
